export const TotalShoes = [
  {
    id: 1,
    image: "src/assets/shoes-one.webp",
    name: "X Lows WASABI",
    category: "comet x",
    singleImg: [
      { img: "src/assets/shoes-one-one.webp" },
      { img: "src/assets/shoes-one-two.webp" },
      { img: "src/assets/shoes-one-three.webp" },
      { img: "src/assets/shoes-one-four.webp" },
    ],
    price: 4299,
    size: [6, 7, 8, 9, 10, 11, 12],
    availability: "out of stock",
  },
  {
    id: 2,
    image: "src/assets/shoes-two.webp",
    name: "X Highs MIRAGE",
    category: "comet x",
    singleImg: [
      { img: "src/assets/shoes-two-one.webp" },
      { img: "src/assets/shoes-two-two.webp" },
      { img: "src/assets/shoes-two-three.webp" },
      { img: "src/assets/shoes-two-four.webp" },
    ],
    price: 4499,
    size: [4, 5, 6, 7, 8, 9, 10, 11],
    availability: "in stock",
  },
  {
    id: 3,
    image: "src/assets/shoes-three.webp",
    name: "X Lows BEACH",
    category: "comet x",

    singleImg: [
      { img: "src/assets/shoes-three-one.jpg" },
      { img: "src/assets/shoes-three-two.webp" },
      { img: "src/assets/shoes-three-three.jpg" },
      { img: "src/assets/shoes-three-four.png" },
    ],
    price: 4299,
    size: [4, 5, 6, 7, 8, 9, 10, 11, 12],
    availability: "out of stock",
  },
  {
    id: 4,
    image: "src/assets/shoes-four.webp",
    name: "Aeon Raven",
    category: "aeon",

    singleImg: [
      { img: "src/assets/shoes-four-one.jpg" },
      { img: "src/assets/shoes-four-two.jpg" },
      { img: "src/assets/shoes-four-three.jpg" },
      { img: "src/assets/shoes-four-four.jpg" },
    ],
    price: 4199,
    size: [4, 5, 6, 7, 8, 9, 10, 11, 12],
    availability: "out of stock",
  },
  {
    id: 5,
    image: "src/assets/shoes-five.webp",
    name: "X Lows DARK",
    category: "comet x",

    singleImg: [
      { img: "src/assets/shoes-five-one.jpg" },
      { img: "src/assets/shoes-five-two.jpg" },
      { img: "src/assets/shoes-five-three.jpg" },
      { img: "src/assets/shoes-five-four.jpg" },
    ],
    price: 4299,
    size: [4, 5, 6, 7, 8, 9, 10],
    availability: "in stock",
  },
  {
    id: 6,
    image: "src/assets/shoes-six.webp",
    name: "Aeon Azure",
    category: "aeon",

    singleImg: [
      { img: "src/assets/shoes-six-one.jpg" },
      { img: "src/assets/shoes-six-two.jpg" },
      { img: "src/assets/shoes-six-three.jpg" },
      { img: "src/assets/shoes-six-four.jpg" },
    ],
    price: 4199,
    size: [4, 5, 6, 7, 8, 9, 10],
    availability: "in stock",
  },
  {
    id: 7,
    image: "src/assets/shoes-seven.jpg",
    name: "Aeon Turquoise",
    category: "aeon",
    singleImg: [
      { img: "src/assets/shoes-seven-one.jpg" },
      { img: "src/assets/shoes-seven-two.jpg" },
      { img: "src/assets/shoes-seven-three.jpg" },
      { img: "src/assets/shoes-seven-four.png" },
    ],
    price: 4199,
    size: [4, 5, 6, 7, 8, 9, 10, 11, 12],
    availability: "in stock",
  },
  {
    id: 8,
    image: "src/assets/shoes-eight.png",
    name: "SPACEBOUND W",
    category: "drops",
    singleImg: [
      { img: "src/assets/shoes-eight-one.png" },
      { img: "src/assets/shoes-eight-two.jpg" },
      { img: "src/assets/shoes-eight-three.png" },
      { img: "src/assets/shoes-eight-four.jpg" },
    ],
    price: 4999,
    size: [4, 5, 6, 7, 8, 9, 10, 11, 12],
    availability: "in stock",
  },
  {
    id: 9,
    image: "src/assets/shoes-nine.webp",
    name: "Aeon Butternut",
    category: "aeon",
    singleImg: [
      { img: "src/assets/shoes-nine-one.webp" },
      { img: "src/assets/shoes-nine-two.jpg" },
      { img: "src/assets/shoes-nine-three.jpg" },
      { img: "src/assets/shoes-nine-four.png" },
    ],
    price: 4199,
    size: [7, 8, 9, 10, 11, 12],
    availability: "out of stock",
  },
  {
    id: 10,
    image: "src/assets/shoes-ten.webp",
    name: "TUXEDO",
    category: "drops",
    singleImg: [
      { img: "src/assets/shoes-ten-one.jpg" },
      { img: "src/assets/shoes-ten-two.jpg" },
      { img: "src/assets/shoes-ten-three.jpg" },
      { img: "src/assets/shoes-ten-four.jpg" },
    ],
    price: 4299,
    size: [8, 9, 10, 11, 12],
    availability: "out of stock",
  },
  {
    id: 11,
    image: "src/assets/Slides-one.jpg",
    name: "Slides FORST",
    category: "slides",
    singleImg: [
      { img: "src/assets/slides-one-one.webp" },
      { img: "src/assets/slides-one-two.jpg" },
      { img: "src/assets/slides-one-three.jpg" },
      { img: "src/assets/slides-one-four.jpg" },
    ],
    price: 4299,
    size: [10, 11, 12],
    availability: "in stock",
  },
  {
    id: 12,
    image: "src/assets/Slides-two.jpg",
    name: "Slides LIME",
    category: "slides",
    singleImg: [
      { img: "src/assets/slides-two-one.jpg" },
      { img: "src/assets/slides-two-two.jpg" },
      { img: "src/assets/slides-two-three.jpg" },
      { img: "src/assets/slides-two-four.jpg" },
    ],
    price: 4299,
    size: [8, 9, 10, 11, 12],
    availability: "in stock",
  },
  {
    id: 13,
    image: "src/assets/Slides-three.jpg",
    name: "Slides LUNA",
    category: "slides",
    singleImg: [
      { img: "src/assets/slides-three-one.jpg" },
      { img: "src/assets/slides-three-two.jpg" },
      { img: "src/assets/slides-three-three.jpg" },
      { img: "src/assets/slides-three-four.jpg" },
    ],
    price: 4299,
    size: [4, 5, 6, 7, 8, 9, 10, 11, 12],
    availability: "out of stock",
  },
  {
    id: 14,
    image: "src/assets/Slides-four.jpg",
    name: "Slides DUSK",
    category: "slides",
    singleImg: [
      { img: "src/assets/slides-four-one.jpg" },
      { img: "src/assets/slides-four-two.jpg" },
      { img: "src/assets/slides-four-three.jpg" },
      { img: "src/assets/slides-four-four.jpg" },
    ],
    price: 4299,
    size: [4, 5, 6, 7, 8, 9, 10, 11, 12],
    availability: "in stock",
  },
  {
    id: 15,
    image: "src/assets/Slides-five.jpg",
    name: "Slides AQUA",
    category: "slides",
    singleImg: [
      { img: "src/assets/slides-five-one.jpg" },
      { img: "src/assets/slides-five-two.jpg" },
      { img: "src/assets/slides-five-three.jpg" },
      { img: "src/assets/slides-five-four.jpg" },
    ],
    price: 4299,
    size: [6, 7, 8, 9, 10, 11],
    availability: "in stock",
  },
];
